services:
  app:
    build: .
    volumes:
      - .:/app
    command: ["sh", "-c", "$APP_COMMAND"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      APP_COMMAND: ${APP_COMMAND}

    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data

volumes:
  postgres-data:
