version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: npm run start
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres:5432/production
      NODE_ENV: production
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data

volumes:
  postgres-data:
